# Generated by Django 4.0.4 on 2022-05-08 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumer_app', '0002_business_dosing_podtype_alter_dispenser_consumer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='docs_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pod',
            name='consumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consumer_app.consumer'),
        ),
        migrations.AlterField(
            model_name='pod',
            name='remainder',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='podtype',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consumer_app.company'),
        ),
        migrations.AlterField(
            model_name='podtype',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='podtype',
            name='substance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='podtype',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
