# Generated by Django 4.0.4 on 2022-04-21 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.account')),
                ('residence', models.CharField(max_length=50)),
                ('height', models.DecimalField(decimal_places=3, max_digits=6)),
                ('weight', models.IntegerField()),
                ('units', models.IntegerField(choices=[(1, 'Metric'), (2, 'Imperial')])),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')])),
            ],
        ),
        migrations.CreateModel(
            name='Dispenser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_num', models.CharField(max_length=100, unique=True)),
                ('version', models.CharField(max_length=50)),
                ('registration_date', models.DateTimeField(default=None, null=True)),
                ('consumer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consumer_app.consumer')),
            ],
        ),
    ]
