# Generated by Django 4.0.4 on 2022-05-06 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('consumer_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('docs_path', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Dosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('substance', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='dispenser',
            name='consumer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consumer_app.consumer'),
        ),
        migrations.AlterField(
            model_name='dispenser',
            name='registration_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='consumer_app.business')),
            ],
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.account')),
                ('can_appoint_reps', models.BooleanField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumer_app.business')),
            ],
        ),
        migrations.CreateModel(
            name='Regimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('time', models.TimeField()),
                ('consumer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consumer_app.consumer')),
                ('pod_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumer_app.podtype')),
            ],
        ),
        migrations.CreateModel(
            name='Pod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_num', models.CharField(max_length=100, unique=True)),
                ('remainder', models.IntegerField()),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumer_app.consumer')),
                ('pod_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumer_app.podtype')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('dosing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consumer_app.dosing')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.CharField(max_length=200)),
                ('dosing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consumer_app.dosing')),
            ],
        ),
        migrations.AddField(
            model_name='dosing',
            name='pod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumer_app.pod'),
        ),
        migrations.AddField(
            model_name='podtype',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumer_app.company'),
        ),
    ]
